[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/poll/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/create"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"